#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Priority of delivery of the activity to the email server.
	/// </summary>
	
	public enum activitypointer_deliveryprioritycode
	{
		
		
		Low = 0,
		
		
		Normal = 1,
		
		
		High = 2,
	}
}
#pragma warning restore CS1591
