#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Type of entity with which the activity attachment is associated.
	/// </summary>
	
	public enum activityfileattachment_objectcode
	{
		
		/// <summary>
		/// Post
		/// </summary>
		
		Post = 8000,
		
		/// <summary>
		/// Post Comment
		/// </summary>
		
		PostComment = 8005,
	}
}
#pragma warning restore CS1591
