#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Type of activity.
	/// </summary>
	
	public enum activitypointer_activitytypecode
	{
		
		
		Fax = 4204,
		
		
		PhoneCall = 4210,
		
		
		Email = 4202,
		
		
		Letter = 4207,
		
		
		Appointment = 4201,
		
		
		Task = 4212,
		
		
		RecurringAppointment = 4251,
		
		
		Teamschat = 10133,
		
		
		InviteRedemption = 10264,
		
		
		PortalComment = 10265,
	}
}
#pragma warning restore CS1591
