#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	
	public enum aipluginsubtype
	{
		
		
		Dataverse = 0,
		
		
		CertifiedConnector = 1,
		
		
		QA = 2,
		
		
		Flow = 3,
		
		
		Prompt = 4,
		
		
		Conversational = 5,
		
		
		CustomApi = 6,
		
		
		RestApi = 7,
		
		
		CustomConnector = 8,
	}
}
#pragma warning restore CS1591
