#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	
	public enum aiplugintype
	{
		
		
		Dataverse = 0,
		
		
		CustomConnector = 1,
		
		
		Connector = 2,
		
		
		Flow = 3,
	}
}
#pragma warning restore CS1591
