#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Type of Reuse Policy associated with Copilot Studio copilot components.
	/// </summary>
	
	public enum botcomponentreusepolicy
	{
		
		/// <summary>
		/// Not Reusable. By default, a copilot component is not reusable and Reuse Policy is None
		/// </summary>
		
		None = 0,
		
		/// <summary>
		/// Is required by one or more Public copilot component, but is not directly invokable or visible
		/// </summary>
		
		Private = 1,
		
		/// <summary>
		/// Visible shared / reusable copilot component for use in all bots in the environment
		/// </summary>
		
		Public = 2,
	}
}
#pragma warning restore CS1591
