#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	
	public enum botcomponentcollectionsharingroletype
	{
		
		/// <summary>
		/// Copilot user has access to the content of the component collection
		/// </summary>
		
		Copilotuser = 1,
		
		/// <summary>
		/// Has access to the content of the component collection and can add component collection to the copilot
		/// </summary>
		
		Componentcollectionuser = 2,
		
		/// <summary>
		/// Can author the component collection
		/// </summary>
		
		Componentcollectionauthor = 3,
	}
}
#pragma warning restore CS1591
