#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Select the records to send the direct email to
	/// </summary>
	
	public enum bulkemail_recipients
	{
		
		/// <summary>
		/// Send direct email only to the records you selected on this page.
		/// </summary>
		
		Selectedrecordsoncurrentpage = 1,
		
		/// <summary>
		/// Send direct email to all the records on this page.
		/// </summary>
		
		Allrecordsoncurrentpage = 2,
		
		/// <summary>
		/// Send direct email to all the records on all the pages in the current view.
		/// </summary>
		
		Allrecordsonallpages = 3,
	}
}
#pragma warning restore CS1591
