#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	
	public enum capability
	{
		
		
		composite = 118690000,
		
		
		tabular = 118690001,
		
		
		blob = 118690002,
		
		
		gateway = 118690003,
		
		
		cloud = 118690004,
		
		
		actions = 118690005,
	}
}
#pragma warning restore CS1591
