#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	
	public enum chatbotlanguage
	{
		
		
		English = 1033,
		
		
		Spanish = 1034,
		
		
		Portuguese_Brazilian = 1046,
		
		
		French = 1036,
		
		
		Dutch = 1043,
		
		
		Norwegian = 1044,
		
		
		Danish = 1030,
		
		
		Swedish = 1053,
		
		
		Italian = 1040,
		
		
		German = 1031,
		
		
		Chinese_Simplified = 2052,
		
		
		Chinese_Traditional = 1028,
		
		
		Arabic = 1025,
		
		
		Japanese = 1041,
		
		
		Korean = 1042,
		
		
		Hindi = 1081,
		
		
		Indonesian = 1057,
		
		
		Russian = 1049,
		
		
		Polish = 1045,
		
		
		Turkish = 1055,
		
		
		Thai = 1054,
		
		
		Finnish = 1035,
		
		
		Greek = 1032,
		
		
		Czech = 1029,
		
		
		English_UnitedKingdom = 2057,
		
		
		French_Canada = 3084,
		
		
		Spanish_UnitedStates = 21514,
		
		
		English_Australia = 3081,
	}
}
#pragma warning restore CS1591
