#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Categories for connection roles.
	/// </summary>
	
	public enum connectionrole_category
	{
		
		
		Business = 1,
		
		
		Family = 2,
		
		
		Social = 3,
		
		
		Sales = 4,
		
		
		Other = 5,
		
		
		Stakeholder = 1000,
		
		
		SalesTeam = 1001,
		
		
		Service = 1002,
	}
}
#pragma warning restore CS1591
