#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Custom API Field Types
	/// </summary>
	
	public enum customapifieldtype
	{
		
		
		Boolean = 0,
		
		
		DateTime = 1,
		
		
		Decimal = 2,
		
		
		Entity = 3,
		
		
		EntityCollection = 4,
		
		
		EntityReference = 5,
		
		
		Float = 6,
		
		
		Integer = 7,
		
		
		Money = 8,
		
		
		Picklist = 9,
		
		
		String = 10,
		
		
		StringArray = 11,
		
		
		Guid = 12,
	}
}
#pragma warning restore CS1591
