#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// How would you like to delete this series?
	/// </summary>
	
	public enum delete_recurringappointmentmaster
	{
		
		/// <summary>
		/// Delete all instances
		/// </summary>
		
		Allinstances = 1,
		
		/// <summary>
		/// Delete all series except the past appointments
		/// </summary>
		
		Theseriesleavepastappointments = 2,
	}
}
#pragma warning restore CS1591
