#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Authentication protocol used when connecting to the email server.
	/// </summary>
	
	public enum emailserverprofile_authenticationprotocol
	{
		
		
		AutoDetect = 0,
		
		
		Negotiate = 1,
		
		
		NTLM = 2,
		
		
		Basic = 3,
		
		
		OAuth = 4,
	}
}
#pragma warning restore CS1591
