#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Field permission to read unmasked values.
	/// </summary>
	
	public enum field_security_permission_readunmasked
	{
		
		
		NotAllowed = 0,
		
		
		OneRecord = 1,
		
		
		AllRecords = 3,
	}
}
#pragma warning restore CS1591
