#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Full Sync Status for Data Sync Framework
	/// </summary>
	
	public enum fullsyncstate
	{
		
		
		NotInitialized = 0,
		
		
		Initiating = 1,
		
		
		InProgress = 2,
		
		
		Completed = 3,
		
		
		Invalid = 4,
		
		
		AcceptMerge = 5,
		
		
		Failed = 6,
	}
}
#pragma warning restore CS1591
