#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Expiration State
	/// </summary>
	
	public enum knowledgearticle_expirationstate
	{
		
		
		Expired = 4,
		
		
		Published = 3,
		
		
		Archived = 5,
	}
}
#pragma warning restore CS1591
