#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Data type of the amount.
	/// </summary>
	
	public enum metric_goaltype
	{
		
		
		Money = 0,
		
		
		Decimal = 1,
		
		
		Integer = 2,
	}
}
#pragma warning restore CS1591
