#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// List of Mobile Offline Enabled Entities.
	/// </summary>
	
	public enum mobileofflineenabledentities
	{
		
		
		Account = 1,
		
		
		Contact = 2,
		
		
		Note = 5,
		
		
		User = 8,
		
		
		Team = 9,
		
		
		Attachment = 1001,
		
		
		Queue = 2020,
		
		
		QueueItem = 2029,
		
		
		Appointment = 4201,
		
		
		Email = 4202,
		
		
		Task = 4212,
		
		
		SLAKPIInstance = 9752,
		
		
		ActivityFileAttachment = 10132,
		
		
		KnowledgeArticleImage = 10141,
		
		
		KnowledgeArticleAttachment = 10147,
		
		
		OrganizationDataSyncFnoState = 10166,
		
		
		OrganizationDataSyncState = 10167,
		
		
		ImageDescriptor = 1007,
	}
}
#pragma warning restore CS1591
