#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// The state of the dataflow template
	/// </summary>
	
	public enum msdyn_dataflowtemplatestate
	{
		
		
		Draft = 100000000,
		
		
		Active = 100000001,
		
		
		Published = 100000002,
		
		
		Deprecated = 100000003,
	}
}
#pragma warning restore CS1591
