#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	
	public enum msdyn_numberofsearchresults
	{
		
		
		_10 = 0,
		
		
		_15 = 1,
		
		
		_20 = 2,
		
		
		_25 = 3,
		
		
		_30 = 4,
		
		
		_40 = 5,
		
		
		_50 = 6,
	}
}
#pragma warning restore CS1591
