#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Option set for selecting the type of the office document.
	/// </summary>
	
	public enum officedocument_documenttype
	{
		
		
		MicrosoftExcel = 1,
		
		
		MicrosoftWord = 2,
	}
}
#pragma warning restore CS1591
