#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Application Based Access Control Mode. 0 is Disabled, 1 is Enabled, 2 is audit mode, 3 is Enabled for roles
	/// </summary>
	
	public enum organization_applicationbasedaccesscontrolmode
	{
		
		
		Disabled = 0,
		
		
		Enabled = 1,
		
		
		AuditMode = 2,
		
		
		Enabledforroles = 3,
	}
}
#pragma warning restore CS1591
