#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Lookback referenced by configuration.
	/// </summary>
	
	public enum orginsightsconfiguration_lookback
	{
		
		
		_2H = 1,
		
		
		_48H = 2,
		
		
		_7D = 3,
		
		
		_30D = 4,
	}
}
#pragma warning restore CS1591
