#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Plot Option referenced by configuration.
	/// </summary>
	
	public enum orginsightsconfiguration_plotoption
	{
		
		
		Line = 1,
		
		
		Column = 2,
		
		
		Area = 3,
		
		
		Pie = 4,
		
		
		Bar = 5,
		
		
		Donut = 6,
		
		
		Infocard = 7,
		
		
		List = 8,
		
		
		DoubleDonut = 9,
		
		
		LinearGauge = 10,
		
		
		Bubble = 11,
	}
}
#pragma warning restore CS1591
