#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	
	public enum photo_resolution
	{
		
		
		DeviceDefault = 0,
		
		
		_640x480 = 1,
		
		
		_1024x768 = 2,
		
		
		_1600x1200 = 3,
		
		
		_2048x1536 = 4,
		
		
		_2592x1936 = 5,
	}
}
#pragma warning restore CS1591
