#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Power Pages Languages
	/// </summary>
	
	public enum powerpagelanguages
	{
		
		
		Arabic = 1025,
		
		
		BasqueBasque = 1069,
		
		
		BulgarianBulgaria = 1026,
		
		
		CatalanCatalan = 1027,
		
		
		ChineseChina = 2052,
		
		
		ChineseHongKongSAR = 3076,
		
		
		ChineseTraditional = 1028,
		
		
		CroatianCroatia = 1050,
		
		
		CzechCzechRepublic = 1029,
		
		
		DanishDenmark = 1030,
		
		
		DutchNetherlands = 1043,
		
		
		English = 1033,
		
		
		EstonianEstonia = 1061,
		
		
		FinnishFinland = 1035,
		
		
		FrenchFrance = 1036,
		
		
		GalicianSpain = 1110,
		
		
		GermanGermany = 1031,
		
		
		GreekGreece = 1032,
		
		
		Hebrew = 1037,
		
		
		HindiIndia = 1081,
		
		
		HungarianHungary = 1038,
		
		
		IndonesianIndonesia = 1057,
		
		
		ItalianItaly = 1040,
		
		
		JapaneseJapan = 1041,
		
		
		KazakhKazakhstan = 1087,
		
		
		KoreanKorea = 1042,
		
		
		LatvianLatvia = 1062,
		
		
		LithuanianLithuania = 1063,
		
		
		MalayMalaysia = 1086,
		
		
		Norwegian_BokmlNorway = 1044,
		
		
		PolishPoland = 1045,
		
		
		PortugueseBrazil = 1046,
		
		
		PortuguesePortugal = 2070,
		
		
		RomanianRomania = 1048,
		
		
		RussianRussia = 1049,
		
		
		Serbian_CyrillicSerbia = 3098,
		
		
		Serbian_LatinSerbia = 2074,
		
		
		SlovakSlovakia = 1051,
		
		
		SlovenianSlovenia = 1060,
		
		
		Spanish_TraditionalSortSpain = 3082,
		
		
		SwedishSweden = 1053,
		
		
		ThaiThailand = 1054,
		
		
		TurkishTrkiye = 1055,
		
		
		UkrainianUkraine = 1058,
		
		
		VietnameseVietnam = 1066,
	}
}
#pragma warning restore CS1591
