#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	
	public enum powerbimashupparametervaluesource
	{
		
		/// <summary>
		/// The value for the parameter is provided as text
		/// </summary>
		
		Literal = 200000000,
		
		/// <summary>
		/// The value for the parameter is bound to an environment variable
		/// </summary>
		
		EnvironmentVariable = 200000001,
		
		/// <summary>
		/// The value for the parameter is set to the domain of the current environment
		/// </summary>
		
		EnvironmentDomain = 200000002,
	}
}
#pragma warning restore CS1591
