#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Power Pages Component Type
	/// </summary>
	
	public enum powerpagecomponenttype
	{
		
		
		PublishingState = 1,
		
		
		WebPage = 2,
		
		
		WebFile = 3,
		
		
		WebLinkSet = 4,
		
		
		WebLink = 5,
		
		
		PageTemplate = 6,
		
		
		ContentSnippet = 7,
		
		
		WebTemplate = 8,
		
		
		SiteSetting = 9,
		
		
		WebPageAccessControlRule = 10,
		
		
		WebRole = 11,
		
		
		WebsiteAccess = 12,
		
		
		SiteMarker = 13,
		
		
		BasicForm = 15,
		
		
		BasicFormMetadata = 16,
		
		
		List = 17,
		
		
		TablePermission = 18,
		
		
		AdvancedForm = 19,
		
		
		AdvancedFormStep = 20,
		
		
		AdvancedFormMetadata = 21,
		
		
		PollPlacement = 24,
		
		
		AdPlacement = 26,
		
		
		BotConsumer = 27,
		
		
		ColumnPermissionProfile = 28,
		
		
		ColumnPermission = 29,
		
		
		Redirect = 30,
		
		
		PublishingStateTransitionRule = 31,
		
		
		Shortcut = 32,
		
		
		CloudFlow = 33,
		
		
		UXComponent = 34,
	}
}
#pragma warning restore CS1591
