#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Category of the process stage.
	/// </summary>
	
	public enum processstage_category
	{
		
		
		Qualify = 0,
		
		
		Develop = 1,
		
		
		Propose = 2,
		
		
		Close = 3,
		
		
		Identify = 4,
		
		
		Research = 5,
		
		
		Resolve = 6,
		
		
		Approval = 7,
	}
}
#pragma warning restore CS1591
