#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Choose when the appointment should end
	/// </summary>
	
	public enum rangeends_options
	{
		
		/// <summary>
		/// The appointment series never ends
		/// </summary>
		
		Never = 1,
		
		/// <summary>
		/// The appointment series ends after a specified number of occurences
		/// </summary>
		
		Bynumberofoccurrences = 2,
		
		/// <summary>
		/// The appointment series ends by a specied end date
		/// </summary>
		
		Byenddate = 3,
	}
}
#pragma warning restore CS1591
