#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Specifies the month of the year valid for the recurrence pattern.
	/// </summary>
	
	public enum recurrencerule_monthofyear
	{
		
		
		InvalidMonthOfYear = 0,
		
		
		January = 1,
		
		
		February = 2,
		
		
		March = 3,
		
		
		April = 4,
		
		
		May = 5,
		
		
		June = 6,
		
		
		July = 7,
		
		
		August = 8,
		
		
		September = 9,
		
		
		October = 10,
		
		
		November = 11,
		
		
		December = 12,
	}
}
#pragma warning restore CS1591
