#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Options for how often should an appointment repeat?
	/// </summary>
	
	public enum repeatpattern_options
	{
		
		
		Daily = 0,
		
		
		Weekly = 1,
		
		
		Monthly = 2,
		
		
		Yearly = 3,
	}
}
#pragma warning restore CS1591
