#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Type of connection to use with RunDesktopFlow action.
	/// </summary>
	
	public enum rundesktopflowconnectiontype
	{
		
		
		Connection = 1,
		
		
		Connectionreference = 2,
	}
}
#pragma warning restore CS1591
