#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Day of the week used under Monthly/Yearly recurrence patterns
	/// </summary>
	
	public enum sameweekday_options
	{
		
		
		Day = 0,
		
		
		Weekday = 1,
		
		
		WeekendDay = 2,
		
		
		Sunday = 3,
		
		
		Monday = 4,
		
		
		Tuesday = 5,
		
		
		Wednesday = 6,
		
		
		Thursday = 7,
		
		
		Friday = 8,
		
		
		Saturday = 9,
	}
}
#pragma warning restore CS1591
