#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Week of the month used under Monthly/Yearly recurrence patterns
	/// </summary>
	
	public enum sameweekweek_options
	{
		
		/// <summary>
		/// First week of the month
		/// </summary>
		
		First = 1,
		
		/// <summary>
		/// Second week of the month
		/// </summary>
		
		Second = 2,
		
		/// <summary>
		/// Third week of the month
		/// </summary>
		
		Third = 3,
		
		/// <summary>
		/// Fourth week of the month
		/// </summary>
		
		Fourth = 4,
		
		/// <summary>
		/// Last week of the month
		/// </summary>
		
		Last = 5,
	}
}
#pragma warning restore CS1591
