#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Validation status of the record URL.
	/// </summary>
	
	public enum sharepoint_validationstatus
	{
		
		
		NotValidated = 1,
		
		
		InProgress = 2,
		
		
		Invalid = 3,
		
		
		Valid = 4,
		
		
		Couldnotvalidate = 5,
	}
}
#pragma warning restore CS1591
