#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Validation status reason of the record URL.
	/// </summary>
	
	public enum sharepoint_validationstatusreason
	{
		
		
		ThisrecordsURLhasnotbeenvalidated = 1,
		
		
		ThisrecordsURLisvalid = 2,
		
		
		ThisrecordsURLisnotvalid = 3,
		
		
		TheURLschemesofMicrosoftDynamics365andSharePointaredifferent = 4,
		
		
		TheURLcouldnotbeaccessedbecauseofInternetExplorersecuritysettings = 5,
		
		
		Authenticationfailure = 6,
		
		
		Invalidcertificates = 7,
	}
}
#pragma warning restore CS1591
