#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Shows the service type of the SharePoint site
	/// </summary>
	
	public enum sharepointsite_servicetype
	{
		
		
		SharePoint = 0,
		
		
		OneDrive = 1,
		
		
		Sharedwithme = 2,
		
		
		MSTeams = 3,
	}
}
#pragma warning restore CS1591
