#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Post message type private or direct.
	/// </summary>
	
	public enum socialactivity_postmessagetype
	{
		
		
		PublicMessage = 0,
		
		
		PrivateMessage = 1,
	}
}
#pragma warning restore CS1591
