#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Identifies where the social profile originated from, such as Twitter, or FaceBook.
	/// </summary>
	
	public enum socialprofile_community
	{
		
		/// <summary>
		/// Facebook item.
		/// </summary>
		
		Facebook = 1,
		
		/// <summary>
		/// Twitter.
		/// </summary>
		
		Twitter = 2,
		
		/// <summary>
		/// Other default
		/// </summary>
		
		Other = 0,
	}
}
#pragma warning restore CS1591
