#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Synapse Link entity metadata state
	/// </summary>
	
	public enum synapselinkentitymetadatastate
	{
		
		/// <summary>
		/// None state for flag enumeration. Not a valid state for usage
		/// </summary>
		
		None = 0,
		
		/// <summary>
		/// Not created
		/// </summary>
		
		NotCreated = 1,
		
		/// <summary>
		/// Metadata creating
		/// </summary>
		
		MetadataCreating = 2,
		
		/// <summary>
		/// Relationship creating
		/// </summary>
		
		RelationshipCreating = 4,
		
		/// <summary>
		/// Created
		/// </summary>
		
		Created = 8,
		
		/// <summary>
		/// Failure
		/// </summary>
		
		Failure = 16,
	}
}
#pragma warning restore CS1591
