#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Synapse Link schedule recurrence unit
	/// </summary>
	
	public enum synapselinkschedulerecurrenceunit
	{
		
		/// <summary>
		/// None
		/// </summary>
		
		None = 0,
		
		/// <summary>
		/// Minute
		/// </summary>
		
		Minute = 1,
		
		/// <summary>
		/// Hour
		/// </summary>
		
		Hour = 2,
		
		/// <summary>
		/// Day
		/// </summary>
		
		Day = 3,
		
		/// <summary>
		/// Week
		/// </summary>
		
		Week = 4,
		
		/// <summary>
		/// Month
		/// </summary>
		
		Month = 5,
		
		/// <summary>
		/// Year
		/// </summary>
		
		Year = 6,
	}
}
#pragma warning restore CS1591
