#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Synapse Link destination sync state
	/// </summary>
	
	public enum synapselinkdestinationsyncstate
	{
		
		/// <summary>
		/// None
		/// </summary>
		
		None = 0,
		
		/// <summary>
		/// Not Completed
		/// </summary>
		
		NotCompleted = 1,
		
		/// <summary>
		/// Completed
		/// </summary>
		
		Completed = 2,
	}
}
#pragma warning restore CS1591
