#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Synapse Link table creation state
	/// </summary>
	
	public enum synapselinksynapsetablecreationstate
	{
		
		/// <summary>
		/// Not started
		/// </summary>
		
		NotStarted = 0,
		
		/// <summary>
		/// In progress
		/// </summary>
		
		InProgress = 1,
		
		/// <summary>
		/// Completed
		/// </summary>
		
		Completed = 2,
		
		/// <summary>
		/// Failed
		/// </summary>
		
		Failed = 3,
	}
}
#pragma warning restore CS1591
