#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Synapse Link external table state
	/// </summary>
	
	public enum synapselinkexternaltablestate
	{
		
		/// <summary>
		/// Not created
		/// </summary>
		
		NotCreated = 0,
		
		/// <summary>
		/// Created
		/// </summary>
		
		Created = 1,
		
		/// <summary>
		/// Failed
		/// </summary>
		
		Failed = 2,
		
		/// <summary>
		/// Deleted
		/// </summary>
		
		Deleted = 3,
		
		/// <summary>
		/// In Progress
		/// </summary>
		
		InProgress = 4,
	}
}
#pragma warning restore CS1591
