#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Synapse Link profile type
	/// </summary>
	
	public enum synapselinkprofiletype
	{
		
		/// <summary>
		/// Synapse Link profile
		/// </summary>
		
		SynapseLink = 0,
		
		/// <summary>
		/// Event Analytics profile
		/// </summary>
		
		EventAnalytics = 1,
	}
}
#pragma warning restore CS1591
