#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Synapse Link entity sync state
	/// </summary>
	
	public enum synapselinkentitysyncstate
	{
		
		/// <summary>
		/// None
		/// </summary>
		
		None = 0,
		
		/// <summary>
		/// Not started
		/// </summary>
		
		NotStarted = 1,
		
		/// <summary>
		/// In progress
		/// </summary>
		
		InProgress = 2,
		
		/// <summary>
		/// Completed
		/// </summary>
		
		Completed = 4,
		
		/// <summary>
		/// Completed with failures
		/// </summary>
		
		CompletedWithFailures = 8,
		
		/// <summary>
		/// Requested initial data
		/// </summary>
		
		RequestedInitialData = 16,
		
		/// <summary>
		/// Paused
		/// </summary>
		
		Paused = 32,
		
		/// <summary>
		/// Post processing
		/// </summary>
		
		PostProcessing = 64,
	}
}
#pragma warning restore CS1591
