#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Synapse Link entity partition strategy
	/// </summary>
	
	public enum synapselinkentitypartitionstrategy
	{
		
		/// <summary>
		/// Year
		/// </summary>
		
		Year = 0,
		
		/// <summary>
		/// Month
		/// </summary>
		
		Month = 1,
		
		/// <summary>
		/// HalfMonth
		/// </summary>
		
		HalfMonth = 2,
		
		/// <summary>
		/// FiveDay
		/// </summary>
		
		FiveDay = 3,
	}
}
#pragma warning restore CS1591
