#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Synapse Link profile state
	/// </summary>
	
	public enum synapselinkprofilestate
	{
		
		/// <summary>
		/// Inactive
		/// </summary>
		
		Inactive = 0,
		
		/// <summary>
		/// Active
		/// </summary>
		
		Active = 1,
		
		/// <summary>
		/// Error
		/// </summary>
		
		Error = 2,
		
		/// <summary>
		/// Deleted
		/// </summary>
		
		Deleted = 3,
		
		/// <summary>
		/// Aborting
		/// </summary>
		
		Aborting = 4,
		
		/// <summary>
		/// Aborted
		/// </summary>
		
		Aborted = 5,
		
		/// <summary>
		/// Suspended
		/// </summary>
		
		Suspended = 6,
		
		/// <summary>
		/// Suspending
		/// </summary>
		
		Suspending = 7,
		
		/// <summary>
		/// Deactivated
		/// </summary>
		
		Deactivated = 8,
	}
}
#pragma warning restore CS1591
