#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Type of entity with which the workflow log is associated.
	/// </summary>
	
	public enum workflowlog_objecttypecode
	{
		
		
		SystemJob = 4700,
		
		
		WorkflowSession = 4710,
		
		
		FlowSession = 4720,
	}
}
#pragma warning restore CS1591
