#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mho.PluginStepsViewer.EarlyBoundTypes
{
	
	
	/// <summary>
	/// Months in a year used under Yearly recurrence pattern
	/// </summary>
	
	public enum yearlymonth_options
	{
		
		/// <summary>
		/// January
		/// </summary>
		
		January = 1,
		
		/// <summary>
		/// February
		/// </summary>
		
		February = 2,
		
		/// <summary>
		/// March
		/// </summary>
		
		March = 3,
		
		/// <summary>
		/// April
		/// </summary>
		
		April = 4,
		
		/// <summary>
		/// May
		/// </summary>
		
		May = 5,
		
		/// <summary>
		/// June
		/// </summary>
		
		June = 6,
		
		/// <summary>
		/// July
		/// </summary>
		
		July = 7,
		
		/// <summary>
		/// August
		/// </summary>
		
		August = 8,
		
		/// <summary>
		/// September
		/// </summary>
		
		September = 9,
		
		/// <summary>
		/// October
		/// </summary>
		
		October = 10,
		
		/// <summary>
		/// November
		/// </summary>
		
		November = 11,
		
		/// <summary>
		/// December
		/// </summary>
		
		December = 12,
	}
}
#pragma warning restore CS1591
